export const zstdCompressAsync: (data: ArrayBuffer, level?: number) => Promise<ArrayBuffer>;
export const zstdDecompressAsync: (data: ArrayBuffer) => Promise<ArrayBuffer>;
export const lz4CompressAsync: (data: ArrayBuffer, level?: number) => Promise<ArrayBuffer>;
export const lz4DecompressAsync: (data: ArrayBuffer) => Promise<ArrayBuffer>;
export const version: () => string;
export const getSupportedFormats: () => string[];
export const detectFormat: (data: ArrayBuffer) => string;
export const snappyCompressAsync: (data: ArrayBuffer) => Promise<ArrayBuffer>;
export const snappyDecompressAsync: (data: ArrayBuffer) => Promise<ArrayBuffer>;